### PR TITLE
Packing Format Generator

### PR DESCRIPTION
**Pull request by raegand**
Created a file that opens a file and generates the packing format based on what is in the file.
Just thought that you should take a look at what I've done for this before adding it to the Data-Translator file.

### CODE REVIEW

**Comment by FFAxKenny** [comment]
Thanks! 

This is a good start, but keep in mind that we eventually want to be able to specify enough information in the configuration file that we can unpack and then store it into a database as well. To be able to store into a database you'll need the column name that is associated with that data element as well.

It would be good to have that functionality by the end of the semester. You're also free to use a data format that is already available like JSON or YAML.

**Comment by FFAxKenny** [comment]
@raegand: can you clean the commenting a little more on this request and then submit another one?

For commenting, you should avoid being too verbose if the code already describes it in a clear way. It's good to answer the questions "why", rather than "what". 

For example, 

    #Open file to read
    file = open(file, 'r')

The line `file = open(file, 'r')` already has most of the words from the comment above it. 

Let me know if you have any questions though.

**Comment by raegand** [comment]
I do have one question.  Where would I be able to find the JSON and YAML format in the repository so I can take a look at it and see if I can use it?

**Comment by FFAxKenny** [comment]
@raegand: there isn't any example in the repository - part of your assignment is to research and design this.

**Pull request closed without merging**
